//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public string CommentID { get; set; }
        public string OfferID { get; set; }
        public string PostedBy { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
    
        public virtual Offers Offers { get; set; }
        public virtual Users Users { get; set; }
    }
}
