//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopTime.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDBEntities : DbContext
    {
        public ShopDBEntities()
            : base("name=ShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<OfferRaiting> OfferRaiting { get; set; }
        public virtual DbSet<Offers> Offers { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<UserRaiting> UserRaiting { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
