//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRaiting
    {
        public string UserID { get; set; }
        public string VoterID { get; set; }
        public Nullable<float> Rating { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
