//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comments = new HashSet<Comments>();
            this.OfferRaiting = new HashSet<OfferRaiting>();
            this.Offers = new HashSet<Offers>();
            this.Orders = new HashSet<Orders>();
            this.UserRaiting = new HashSet<UserRaiting>();
        }
    
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string UserRights { get; set; }
        public string AvatarURL { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<OfferRaiting> OfferRaiting { get; set; }
        public virtual ICollection<Offers> Offers { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<UserRaiting> UserRaiting { get; set; }
    }
}
